#!/bin/sh

set -e

PKG="musica"
case "$1" in
	remove)
		if [ -e "/etc/apache2/sites-enabled/${PKG}.conf" ]; then
			a2dissite $PKG
		fi
	;;
	purge)
		rm -f /var/lib/$PKG/* /etc/apache2/sites-available/${PKG}.conf
		rm -rf /etc/$PKG/
		[ -h /usr/share/$PKG/music ] && rm -f /usr/share/$PKG/music || true
	;;
esac

#DEBHELPER#
